CREATE TABLE BOOKING 
(
  BOOKING_ID NUMBER NOT NULL 
, BOOKING_GUEST_ID NUMBER NOT NULL 
, BOOKING_PLACE_ID NUMBER NOT NULL 
, BOOKING_CHECK_IN DATE NOT NULL 
, BOOKING_CHECK_OUT DATE NOT NULL 
, CONSTRAINT BOOKING_PK PRIMARY KEY 
  (
    BOOKING_ID 
  )
  ENABLE 
);