CREATE TABLE PLACE 
(
  PLACE_ID NUMBER NOT NULL 
, PLACE_OWNER_ID NUMBER NOT NULL 
, PLACE_NAME VARCHAR2(200 BYTE) NOT NULL 
, PLACE_MAX_PEOPLE NUMBER NOT NULL 
, PLACE_DESCRIPTION CLOB 
, PLACE_COST FLOAT(126) NOT NULL 
, PLACE_COUNTRY VARCHAR2(50 BYTE) NOT NULL 
, PLACE_CITY VARCHAR2(50 BYTE) NOT NULL 
, PLACE_STREET VARCHAR2(100 BYTE) NOT NULL 
, CONSTRAINT PLACE_PK PRIMARY KEY 
  (
    PLACE_ID 
  )
  ENABLE 
);