CREATE TABLE USERS 
(
  USER_ID NUMBER NOT NULL 
, USER_FIRST_NAME VARCHAR2(30 BYTE) NOT NULL 
, USER_LAST_NAME VARCHAR2(30 BYTE) NOT NULL 
, USER_EMAIL VARCHAR2(50 BYTE) NOT NULL 
, USER_PASSWORD VARCHAR2(50 BYTE) NOT NULL 
, USER_GENDER VARCHAR2(20 BYTE) 
, USER_AGE NUMBER 
, USER_CARD_NUMBER NUMBER 
, USER_LOGIN VARCHAR2(30 BYTE) NOT NULL 
, USER_RESET_KEY VARCHAR2(50 BYTE) 
, CONSTRAINT USERS_PK PRIMARY KEY 
  (
    USER_ID 
  )
  ENABLE 
);